services:
  - type: web
    name: draxen-ai-server
    env: node
    region: frankfurt
    plan: free
    buildCommand: npm install && npm run build:server
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    healthCheckPath: /

  - type: web
    name: draxen-ai-client
    env: static
    region: frankfurt
    plan: free
    buildCommand: npm install && npm run build:client
    staticPublishPath: ./client/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://draxen-ai-server.onrender.com
      - key: VITE_APP_NAME
        value: Draxen AI
      - key: VITE_APP_VERSION
        value: 1.0.0
      - key: VITE_APP_ENVIRONMENT
        value: production
      - key: VITE_ENABLE_AUTH
        value: "true"
      - key: VITE_ENABLE_ANALYTICS
        value: "true"
